"""Tests for ``app.rag.parser_pdf_v2`` (Phase C.1: PyMuPDF + pdfplumber).

These tests use four small PDF fixtures generated by PyMuPDF at build
time:

* ``sample_text.pdf``    — pure text body, multiple paragraphs.
* ``sample_table.pdf``   — text body + a bordered 3-column table.
* ``sample_complex.pdf`` — 5-page multi-chapter layout.
* ``sample_scan.pdf``    — image-only page (no embedded text).

All tests skip cleanly if the corresponding fixture is missing, so
they're safe to run before fixture generation.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from app.rag.parser_pdf_v2 import (
    PYMUPDF_AVAILABLE,
    parse_pdf_v2,
    _parse_with_pypdf_fallback,
)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def fixtures_dir() -> Path:
    """Path to ``tests/fixtures`` (Phase C.1 PDF samples)."""
    return Path(__file__).parent / "fixtures"


# ---------------------------------------------------------------------------
# Per-fixture extraction behaviour
# ---------------------------------------------------------------------------


def test_parse_text_pdf_returns_sections(fixtures_dir: Path) -> None:
    """A text PDF yields at least one section with non-empty text."""
    p = fixtures_dir / "sample_text.pdf"
    if not p.exists():
        pytest.skip(f"fixture missing: {p}")
    sections = parse_pdf_v2(p)
    assert len(sections) >= 1
    assert all(s["text"] for s in sections)
    assert all(s["page"] >= 1 for s in sections)


def test_parse_table_pdf_extracts_tables(fixtures_dir: Path) -> None:
    """The table PDF has at least one page with a non-empty ``tables`` list."""
    p = fixtures_dir / "sample_table.pdf"
    if not p.exists():
        pytest.skip(f"fixture missing: {p}")
    sections = parse_pdf_v2(p)
    table_sections = [s for s in sections if s.get("tables")]
    assert len(table_sections) >= 1
    assert len(table_sections[0]["tables"]) >= 1
    # The header row is the first row of the first table.
    header = table_sections[0]["tables"][0][0]
    assert "Name" in header


def test_parse_complex_pdf_handles_multiple_pages(fixtures_dir: Path) -> None:
    """The 5-page complex PDF yields multiple sections and does not crash."""
    p = fixtures_dir / "sample_complex.pdf"
    if not p.exists():
        pytest.skip(f"fixture missing: {p}")
    sections = parse_pdf_v2(p)
    assert len(sections) >= 1
    # All page numbers are 1-based and strictly increasing.
    pages = [s["page"] for s in sections]
    assert pages == sorted(set(pages))


def test_parse_scan_pdf_does_not_crash(fixtures_dir: Path) -> None:
    """A scan-only PDF may yield zero sections but must not raise."""
    p = fixtures_dir / "sample_scan.pdf"
    if not p.exists():
        pytest.skip(f"fixture missing: {p}")
    sections = parse_pdf_v2(p)
    # The contract is "returns a list" — it may legitimately be empty
    # when no embedded text is present. Phase C.2 will fill this via
    # Tesseract OCR.
    assert isinstance(sections, list)


# ---------------------------------------------------------------------------
# Error handling
# ---------------------------------------------------------------------------


def test_pdf_not_found_raises() -> None:
    """A missing path raises ``FileNotFoundError``."""
    with pytest.raises(FileNotFoundError):
        parse_pdf_v2("/nonexistent/path.pdf")


def test_pypdf_fallback_raises_for_corrupt_pdf(tmp_path: Path) -> None:
    """The pypdf fallback raises ``RuntimeError`` for an unparseable file.

    Behavioural parity with ``parser_pdf.parse_pdf`` is intentional:
    the fallback path inside v2 is still a PDF parser, and a
    completely unparseable file is the caller's problem to surface.
    Per-page errors are still caught individually — only "file is
    not a PDF" raises.
    """
    bad = tmp_path / "not_a_real.pdf"
    bad.write_bytes(b"this is definitely not a PDF header\n")
    with pytest.raises(RuntimeError):
        _parse_with_pypdf_fallback(bad)


# ---------------------------------------------------------------------------
# Section contract
# ---------------------------------------------------------------------------


def test_section_metadata_includes_extractor(fixtures_dir: Path) -> None:
    """Every section carries ``metadata.extractor`` from a known set."""
    p = fixtures_dir / "sample_text.pdf"
    if not p.exists():
        pytest.skip(f"fixture missing: {p}")
    sections = parse_pdf_v2(p)
    valid_extractors = ("pymupdf", "pymupdf+pdfplumber", "pypdf_fallback")
    for s in sections:
        assert "metadata" in s
        assert "extractor" in s["metadata"]
        assert s["metadata"]["extractor"] in valid_extractors


def test_section_images_field_is_list(fixtures_dir: Path) -> None:
    """Every section carries an ``images`` list (possibly empty)."""
    p = fixtures_dir / "sample_text.pdf"
    if not p.exists():
        pytest.skip(f"fixture missing: {p}")
    sections = parse_pdf_v2(p)
    for s in sections:
        assert "images" in s
        assert isinstance(s["images"], list)


def test_section_tables_field_is_list(fixtures_dir: Path) -> None:
    """Every section carries a ``tables`` list (possibly empty)."""
    p = fixtures_dir / "sample_text.pdf"
    if not p.exists():
        pytest.skip(f"fixture missing: {p}")
    sections = parse_pdf_v2(p)
    for s in sections:
        assert "tables" in s
        assert isinstance(s["tables"], list)


# ---------------------------------------------------------------------------
# Loader integration
# ---------------------------------------------------------------------------


def test_load_document_dispatches_to_v2_for_pdf(fixtures_dir: Path) -> None:
    """``load_document`` uses parser_pdf_v2 by default for ``.pdf`` files.

    The result must be non-empty and carry the v2 metadata shape.
    """
    from app.rag.loader import load_document

    p = fixtures_dir / "sample_text.pdf"
    if not p.exists():
        pytest.skip(f"fixture missing: {p}")
    sections = load_document(p)  # prefer_v2=True is the default
    assert len(sections) >= 1
    # At least one section must be tagged with an extractor field.
    assert any("extractor" in s.get("metadata", {}) for s in sections)


def test_pymupdf_import_succeeded() -> None:
    """Smoke test: the PyMuPDF import succeeded at module load.

    If this ever fails it means the environment is missing the
    aarch64 wheel; the rest of the v2 path will fall back to pypdf
    gracefully (covered by the test above).
    """
    # We don't *require* PyMuPDF for the tests to pass — the fallback
    # path is the contract — but on a properly-installed environment
    # (Pi 4 aarch64) the wheel is available and we should use it.
    if not PYMUPDF_AVAILABLE:
        pytest.skip("PyMuPDF not installed in this environment; falling back to pypdf")
    import fitz  # noqa: F401  -- import-side-effect check
